### ISSUE TITLE
Unable to connect the bot

### ISSUE THREAD

**Issue by LegendaryLucifer** [woosal1337/Chegg-Discord-BOT-BETA#2]
I just tried connecting the bot to my server & it requires my code grant, please solve this issue 

![Screenshot 2021-01-29 102210](https://user-images.githubusercontent.com/43181865/106300316-f93b8a80-621b-11eb-9e8f-1fbb3fcd3448.png)

**Comment by woosal1337** [comment]
That is because the bot has reached 250 servers, and Discord has to verify the bot. Waiting for the verification.
